name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - '**/README.md'
      - 'LICENSE*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        job:
          - { otp_version: "26", elixir_version: "1.15" }
          - { otp_version: "24", elixir_version: "1.13" }

    name: Linux x86_64 - OTP ${{ matrix.job.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.job.otp_version }}
          elixir-version: ${{ matrix.job.elixir_version }}

      - name: Compile and Test
        run: |
          mix deps.get
          mix test

  macos:
    runs-on: macos-12
    env:
      MIX_ENV: test
      ELIXIR_VERSION: "1.16.2"
    strategy:
      fail-fast: false
      matrix:
        otp_version: ["25.3.2.8", "26.2.2"]

    name: macOS x86_64 - OTP ${{ matrix.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache OTP
        uses: actions/cache@v3
        id: cache-otp
        with:
          path: ./cache/otp
          key: ${{ runner.os }}-otp-${{ matrix.otp_version }}

      - name: Download OTP
        if: steps.cache-otp.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./cache/otp
          curl -fSL https://github.com/cocoa-xu/otp-build/releases/download/v${{ matrix.otp_version }}/otp-x86_64-apple-darwin.tar.gz -o ./cache/otp/otp-v${{ matrix.otp_version }}-x86_64-apple-darwin.tar.gz
          cd ./cache/otp
          tar -xzf otp-v${{ matrix.otp_version }}-x86_64-apple-darwin.tar.gz

      - name: Cache Elixir
        id: cache-elixir
        uses: actions/cache@v4
        with:
          path: ./cache/elixir
          key: ${{ runner.os }}-elixir-${{ env.ELIXIR_VERSION }}

      - name: Download and Compile Elixir
        if: steps.cache-elixir.outputs.cache-hit != 'true'
        run: |
          export PATH=$(pwd)/./cache/otp/usr/local/bin:$(pwd)/./cache/elixir/elixir-${{ env.ELIXIR_VERSION }}/bin:${PATH}
          export ERL_ROOTDIR=$(pwd)/./cache/otp/usr/local/lib/erlang
          mkdir -p ./cache/elixir
          curl -fSL https://github.com/elixir-lang/elixir/archive/refs/tags/v${{ env.ELIXIR_VERSION }}.tar.gz -o ./cache/elixir/elixir-${{ env.ELIXIR_VERSION }}.tar.gz
          cd ./cache/elixir
          tar -xzf elixir-${{ env.ELIXIR_VERSION }}.tar.gz
          cd elixir-${{ env.ELIXIR_VERSION }}
          make compile
          make -j$(sysctl -n hw.ncpu) install

      - name: Install Mix and Rebar
        run: |
          export PATH=$(pwd)/./cache/otp/usr/local/bin:$(pwd)/./cache/elixir/elixir-${{ env.ELIXIR_VERSION }}/bin:${PATH}
          export ERL_ROOTDIR=$(pwd)/./cache/otp/usr/local/lib/erlang
          mix local.hex --force
          mix local.rebar --force

      - name: Compile and Test
        run: |
          export PATH=$(pwd)/./cache/otp/usr/local/bin:$(pwd)/./cache/elixir/elixir-${{ env.ELIXIR_VERSION }}/bin:${PATH}
          export ERL_ROOTDIR=$(pwd)/./cache/otp/usr/local/lib/erlang

          mix deps.get
          mix test
