name: precompile

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: prod
    strategy:
      matrix:
        otp_version: [25]

    name: Linux - OTP ${{ matrix.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: 1.16

      - name: Install system dependecies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential automake autoconf pkg-config bc m4 unzip zip \
            gcc g++ \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
            gcc-riscv64-linux-gnu g++-riscv64-linux-gnu \
            gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu \
            gcc-s390x-linux-gnu g++-s390x-linux-gnu

      - name: Precompile
        run: |
          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix deps.get
          mix elixir_make.precompile

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
            cache/*.sha256

  macos:
    runs-on: macos-12
    env:
      MIX_ENV: prod
      ELIXIR_VERSION: "1.16"
      CC_PRECOMPILER_PRECOMPILE_ONLY_LOCAL: "true"
    strategy:
      matrix:
        job:
          - { otp_version: "25.3", runs-on: macos-12, arch: "x86_64" }
          - { otp_version: "25.3", runs-on: macos-14, arch: "arm64" }

    name: macOS ${{ matrix.job.arch }} - OTP ${{ matrix.job.otp_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Erlang and Elixir
        run: |
          brew install autoconf coreutils curl git openssl wxwidgets asdf ffmpeg eigen
          brew link ffmpeg
          asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git
          asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
          export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
          asdf install erlang ${{ matrix.job.otp_version }}
          asdf install elixir ${{ env.ELIXIR_VERSION }}
          asdf global erlang ${{ matrix.job.otp_version }}
          asdf global elixir ${{ env.ELIXIR_VERSION }}
          source $(brew --prefix asdf)/libexec/asdf.sh
          mix local.hex --force
          mix local.rebar --force

      - name: Precompile
        run: |
          source $(brew --prefix asdf)/libexec/asdf.sh

          export ELIXIR_MAKE_CACHE_DIR=$(pwd)/cache
          mkdir -p "${ELIXIR_MAKE_CACHE_DIR}"
          mix deps.get
          mix elixir_make.precompile

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            cache/*.tar.gz
            cache/*.sha256
